name: ARM CI for Raspberry Pi 4 Bookworm

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup ARM emulation for Raspberry Pi 4 Bookworm
    - uses: pguyot/arm-runner-action@v2
      with:
        cpu: cortex-a7
        cpu_info: cpuinfo/raspberrypi_3b # No specific cpuinfo for Pi 2, but this is compatible
        base_image: raspios_lite:latest # Assuming use of latest 32-bit Raspberry Pi OS
        copy_repository_path: /opt/project
        commands: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libglib2.0-dev libcurl4-openssl-dev libgps-dev
          # Clone and build SDL_gpu as an example of building a dependency from source
          git clone https://github.com/grimfang4/sdl-gpu.git sdl-gpu
          cd sdl-gpu
          cmake -G "Unix Makefiles"
          make
          sudo make install
          # Build your project here
          cd /opt/project
          # Assuming configure script is available
          ./configure
          make
