name: Emulate RPi 4 and Print Hello World

on: 
  push:

jobs:
  setup-and-emulate-rpi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install qemu-system-arm
        run: sudo apt-get update && sudo apt-get install -y qemu-system-arm qemu-efi-aarch64 qemu-utils

      - name: Prepare emulation environment for RPi 4
        run: |
          mkdir -p ~/Projects/rpitest
          git clone https://github.com/dhruvvyas90/qemu-rpi-kernel.git ~/qemu-rpi-kernel
          # Use a kernel and dtb suitable for RPi 4 emulation
          cp ~/qemu-rpi-kernel/kernel-qemu-5.4.51-buster ~/Projects/rpitest/kernel-qemu
          cp ~/qemu-rpi-kernel/versatile-pb.dtb ~/Projects/rpitest/
          # Download and prepare Raspberry Pi OS Lite image
          curl -L -o ~/Projects/rpitest/raspios-lite-arm64.img.xz 'https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64-lite.img.xz'
          xz -d ~/Projects/rpitest/raspios-lite-arm64.img.xz
          mv ~/Projects/rpitest/raspios-lite-arm64.img ~/Projects/rpitest/rpitest.img
          qemu-img convert -f raw -O qcow2 ~/Projects/rpitest/rpitest.img ~/Projects/rpitest/rpitest.qcow2

      - name: Run Emulated RPi 4 and Print Hello World
        run: |
          echo '#!/usr/bin/env bash' > ~/Projects/rpitest/rpistart.sh
          echo 'sudo qemu-system-aarch64 -M virt -m 1G -cpu cortex-a72 -kernel ~/Projects/rpitest/kernel-qemu -drive file=~/Projects/rpitest/rpitest.qcow2,format=qcow2 -net nic -net user -dtb ~/Projects/rpitest/versatile-pb.dtb -serial stdio -append "root=/dev/vda2 panic=1 rootfstype=ext4 rw" -no-reboot' >> ~/Projects/rpitest/rpistart.sh
          chmod +x ~/Projects/rpitest/rpistart.sh
          (cd ~/Projects/rpitest && ./rpistart.sh &) | grep -m1 "Raspberry Pi OS"
          echo "Hello World"
