name: C/C++ CI for ARM on QEMU

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: multiarch/debian-debootstrap:armhf-bookworm
      options: --privileged

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y libsdl2-dev libsdl2-image-dev libglib2.0-dev libcurl4-openssl-dev libgps-dev qemu-user-static
        # Adjust installation commands if necessary for Debian Bookworm ARMhf
    - name: Install SDL_gpu
      run: |
        git clone https://github.com/grimfang4/sdl-gpu.git sdl-gpu
        cd sdl-gpu
        cmake -G "Unix Makefiles"
        make
        make install
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_CI }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Initialize and update git submodules
      run: git submodule update --init --recursive
    - name: Configure sdl-pcf
      run: |
        cd sdl-pcf
        autoreconf -i
        ./configure --with-texture=sdl_gpu
    - name: Download and extract media
      run: |
        wget https://github.com/sam-itt/fg-roam/archive/media.tar.gz
        tar -xf media.tar.gz --strip-components=1 -C fg-roam/
    - name: Build
      run: make
    - name: Upload ARM binary
      uses: actions/upload-artifact@v2
      with:
        name: sofis-linux-arm
        path: ./sofis
